stages:
  data_ingestion:
    cmd: python src/ingestion/data_ingestion.py
    deps:
      - src/ingestion/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/interim

  data_preprocessing:
    cmd: python src/preprocessing/data_preprocessing.py
    deps:
      - data/interim/train.csv
      - data/interim/test.csv
      - src/preprocessing/data_preprocessing.py
    outs:
      - data/processed

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - data/processed/train_processed.csv
      - src/model/model_building.py
    params:
      - model_building.max_features
      - model_building.ngram_range
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    outs:
      - models/sentiment_pipeline.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - models/sentiment_pipeline.pkl
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
      - src/model/model_evaluation.py
    outs:
      - experiment_info.json

  model_registration:
    cmd: python src/model/register_model.py
    deps:
      - experiment_info.json
      - src/model/register_model.py
